id:
  id: workflow1
  name: my first workflow
  description: some generic workflow description
apps:
  - input1
  - output1
connections:
  #connections can only be output->input, never input->output.
  #output->input is eg. source to a processor, or
  #processor->processor, or even processor->output.
  #but input->output is basically a processor of some sort.
  #eg. suppose there's a processor that does json->xml.
  #In that case, the INPUT will be json, and the OUTPUT will
  #be XML. So the processor (i.e. the code) does the input->output
  #conversion. For that reason, connections can only be output->input
  - out: '[input1]-out1'
    in: '[output1]-in1'
stdio:
  #specify to which apps, if any, stdin and stdout should be connected.
  #this is dfferent from connections because connections are from output to input.
  #this is from input->app, or app->output
  in: input1
  out: null

  