id:
  id: app_echo_system
  name:
  description:
workflows:
  - name: workflow_echo_system
    args:
stdio:
  stdin:
    workflow: workflow_echo_system
    msg_type: string
  stdout:
    workflow: workflow_echo_system
    msg_type: string