#note: this config file does NOT need to be in the config directory
#it can be anywhere
server:
  addr: "http://localhost:8080"
broker:
  bind_addr: "0.0.0.0:8888"
apps:
  #format app_name (optional version) [optional instance IDs (comma separated)]
  #if instance IDs are not specified, defaults to 0 only
  - echo (0.0.1) 0,1
routing:
  #format src <types comma separated> [optional routing keys, comma separated] -> dst1[,dst2[,dst3[...]]]
  - echo-0 string -> echo-1
  - echo-1 string -> echo-0

