refresh_rate: 60 seconds

appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console
  file:
    kind: rolling_file
    path: config/logs/logfile.log
    policy:
      trigger:
        kind: size
        limit: 2 mb
      roller:
        kind: fixed_window
        pattern: logs/logfile.log.{}
        count: 5
        base: 1
# Set the default logging level to "warn" and attach the "stdout" appender to the root
root:
  level: info
  appenders:
    - stdout
    - file

loggers:
  file:
    level: info
    appenders:
      - file
