apps:
  #id is mandatory and must be unique
  - id: input1
    #name is optional
    name: reader script
    type: included
    #description is optional
    description: data received from reader script
    #mandatory. can be one or more inputs. can be one or more outputs
    #for instance, maybe there's stdout, and error out.
    #or maybe there's 2 different types of data being output.
    #same applies for input.
    #inputs and outputs can also be one or many i.e. for every named
    #input and/or output, data can come/go to/from one place, or many
    io:
      #the workflow must link this output up to an input.
      #this must be done such that all inputs and outputs are linked
      in: null
      out:
        - id: out1
          type: single
          description: some optional description
          integration:
            type: stdout
            extras: null
  - id: processor1
    name: string processor
    type: included
    description: converts data into strings
    io:
      in:
        - id: in1
          type: single
          description: some optional description
          integration:
            type: stdin
            extras: null
      out:
        - id: out1
          type: single
          description: some optional description
          integration:
            type: stdout
            extras: null
  - id: output1
    name: writer script
    type: included
    description: data written to the writer script
    io:
      in:
        - id: in1
          type: single
          description: some optional description
          integration:
            type: stdout
            extras: null