id:
  id: workflow_echo_internal
  name: simple echo (internal)
  description: some generic workflow description
apps:
  - name: echo_cntr1
    run_type: once
    once_options:
      disabled: false #for debugging
    repeated_options:
    start_stop_options:
    bin:
      name: echo
