id:
  id: workflow_echo_internal
  name: simple echo (internal)
  description: some generic workflow description
apps:
  - run_type: once
    once_options:
    repeated_options:
    start_stop_options:
    bin:
      name: echo
