id:
  id: workflow_echo
  name: simple echo
  description: some generic workflow description
apps:
  #specify the container and app options
  - name: cntr1
    run_type: once
    options: 
    bin:
      name: echo
