routes:
  - src:
      app: webserver_cntr
      types: ["string"]
      rks: ["say_hello"]
    dst:
      - echo_cntr
  - src:
      app: echo_cntr
    dst:
      - webserver_cntr
  - src:
      app: webserver_cntr
      types: ["string"]
      rks: ["say_goodbye"]
    dst:
      - echo_cntr
